CREATE TABLE `video_list` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '视频ID，主键',
  `title` varchar(255) NOT NULL COMMENT '视频标题',
  `description` text COMMENT '视频描述',
  `url` varchar(512) NOT NULL COMMENT '视频URL或存储路径',
  `thumbnail_url` varchar(512) COMMENT '缩略图URL或存储路径',
  `duration` int(11) DEFAULT 0 COMMENT '视频时长（秒）',
  `file_size` bigint(20) DEFAULT 0 COMMENT '文件大小（字节）',
  `category_id` int(11) DEFAULT NULL COMMENT '分类ID，关联分类表',
  `tags` varchar(512) COMMENT '视频标签，多个标签用逗号分隔',
  `views` int(11) DEFAULT 0 COMMENT '观看次数',
  `likes` int(11) DEFAULT 0 COMMENT '点赞数',
  `dislikes` int(11) DEFAULT 0 COMMENT '点踩数',
  `status` tinyint(1) DEFAULT 1 COMMENT '状态：1-发布，0-草稿，-1-删除',
  `is_featured` tinyint(1) DEFAULT 0 COMMENT '是否推荐：1-是，0-否',
  `sort_order` int(11) DEFAULT 0 COMMENT '排序权重',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `published_at` timestamp NULL DEFAULT NULL COMMENT '发布时间',
  `creator_id` int(11) NOT NULL COMMENT '创建者/上传者ID',
  PRIMARY KEY (`id`),
  KEY `idx_category` (`category_id`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_published_at` (`published_at`),
  KEY `idx_creator` (`creator_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='视频列表表';
